name: Input
desription: Yay InputIGNHere's first plugin!
version: 1.0
main: me.inputignhere.inputfun
author: Input aka JasorYEH
website: www.jasoryeh.com
commands:
  test:
    usage: /test
    description: Gives you full health and responds to test message.
  ibelieveicanfly:
    usage: /ibelieveicanfly
    description: I believe I can flyyyyy!
  expplz:
    usage: /expplz
    description: Gives you 30 experience levels!
  derpy:
    usage: /derpy
    description: Derps you!
